package net.salju.trialstowers.init;

import net.salju.trialstowers.Trials;
import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.network.chat.Component;
import net.minecraft.core.registries.Registries;

public class TrialsTabs {
	public static final DeferredRegister<CreativeModeTab> REGISTRY = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, Trials.MODID);
	public static final RegistryObject<CreativeModeTab> TRIALS = REGISTRY.register("trials",
			() -> CreativeModeTab.builder().title(Component.translatable("itemGroup.trials")).icon(() -> new ItemStack(TrialsItems.TRIAL_KEY.get())).displayItems((parameters, tabData) -> {
				tabData.accept(Blocks.TUFF.asItem());
				tabData.accept(TrialsBlocks.TUFF_STAIRS.get().asItem());
				tabData.accept(TrialsBlocks.TUFF_SLAB.get().asItem());
				tabData.accept(TrialsBlocks.TUFF_WALL.get().asItem());
				tabData.accept(TrialsBlocks.CHISELED_TUFF.get().asItem());
				tabData.accept(TrialsBlocks.POLISHED_TUFF.get().asItem());
				tabData.accept(TrialsBlocks.POLISHED_TUFF_STAIRS.get().asItem());
				tabData.accept(TrialsBlocks.POLISHED_TUFF_SLAB.get().asItem());
				tabData.accept(TrialsBlocks.POLISHED_TUFF_WALL.get().asItem());
				tabData.accept(TrialsBlocks.TUFF_BRICKS.get().asItem());
				tabData.accept(TrialsBlocks.TUFF_BRICKS_STAIRS.get().asItem());
				tabData.accept(TrialsBlocks.TUFF_BRICKS_SLAB.get().asItem());
				tabData.accept(TrialsBlocks.TUFF_BRICKS_WALL.get().asItem());
				tabData.accept(TrialsBlocks.CHISELED_TUFF_BRICKS.get().asItem());
				tabData.accept(TrialsBlocks.CHISELED_TUFF_BULB.get().asItem());
				tabData.accept(TrialsBlocks.SPAWNER.get().asItem());
				tabData.accept(TrialsBlocks.VAULT.get().asItem());
				tabData.accept(TrialsBlocks.VAULT_OMNI.get().asItem());
				tabData.accept(TrialsItems.BOLT_TEMPLATE.get());
				tabData.accept(TrialsItems.FLOW_TEMPLATE.get());
				tabData.accept(TrialsItems.BANNER_PATTERN_FLOW.get());
				tabData.accept(TrialsItems.BANNER_PATTERN_GUSTER.get());
				tabData.accept(TrialsBlocks.CRAFTER.get().asItem());
				tabData.accept(TrialsBlocks.HEAVY_CORE.get().asItem());
				tabData.accept(TrialsItems.MACE.get());
				tabData.accept(TrialsItems.BREEZE_ROD.get());
				tabData.accept(TrialsItems.WIND_CHARGE.get());
				tabData.accept(TrialsItems.FLOW_SHERD.get());
				tabData.accept(TrialsItems.GUSTER_SHERD.get());
				tabData.accept(TrialsItems.SCRAPE_SHERD.get());
				tabData.accept(TrialsItems.MUSIC_DISC_CREATOR_BOX.get());
				tabData.accept(TrialsItems.MUSIC_DISC_PRECIPICE.get());
				tabData.accept(TrialsItems.MUSIC_DISC_CREATOR.get());
				tabData.accept(TrialsItems.TRIAL_BOTTLE.get());
				tabData.accept(TrialsItems.TRIAL_KEY.get());
				tabData.accept(TrialsItems.TRIAL_KEY_OMNI.get());
				tabData.accept(TrialsItems.BOGGED_SPAWN_EGG.get());
				tabData.accept(TrialsItems.BREEZE_SPAWN_EGG.get());
			}).build());
			
	public static final RegistryObject<CreativeModeTab> COPPER = REGISTRY.register("copper",
			() -> CreativeModeTab.builder().title(Component.translatable("itemGroup.copper")).icon(() -> new ItemStack(TrialsBlocks.CHISELED_COPPER.get().asItem())).displayItems((parameters, tabData) -> {
				tabData.accept(Blocks.COPPER_BLOCK.asItem());
				tabData.accept(TrialsBlocks.CHISELED_COPPER.get().asItem());
				tabData.accept(TrialsBlocks.COPPER_BULB.get().asItem());
				tabData.accept(Blocks.CUT_COPPER.asItem());
				tabData.accept(Blocks.CUT_COPPER_STAIRS.asItem());
				tabData.accept(Blocks.CUT_COPPER_SLAB.asItem());
				tabData.accept(TrialsBlocks.COPPER_TRAPDOOR.get().asItem());
				tabData.accept(TrialsBlocks.COPPER_DOOR.get().asItem());
				tabData.accept(TrialsBlocks.COPPER_GRATE.get().asItem());
				tabData.accept(Blocks.EXPOSED_COPPER.asItem());
				tabData.accept(TrialsBlocks.EX_CHISELED_COPPER.get().asItem());
				tabData.accept(TrialsBlocks.EX_COPPER_BULB.get().asItem());
				tabData.accept(Blocks.EXPOSED_CUT_COPPER.asItem());
				tabData.accept(Blocks.EXPOSED_CUT_COPPER_STAIRS.asItem());
				tabData.accept(Blocks.EXPOSED_CUT_COPPER_SLAB.asItem());
				tabData.accept(TrialsBlocks.EX_COPPER_TRAPDOOR.get().asItem());
				tabData.accept(TrialsBlocks.EX_COPPER_DOOR.get().asItem());
				tabData.accept(TrialsBlocks.EX_COPPER_GRATE.get().asItem());
				tabData.accept(Blocks.WEATHERED_COPPER.asItem());
				tabData.accept(TrialsBlocks.W_CHISELED_COPPER.get().asItem());
				tabData.accept(TrialsBlocks.W_COPPER_BULB.get().asItem());
				tabData.accept(Blocks.WEATHERED_CUT_COPPER.asItem());
				tabData.accept(Blocks.WEATHERED_CUT_COPPER_STAIRS.asItem());
				tabData.accept(Blocks.WEATHERED_CUT_COPPER_SLAB.asItem());
				tabData.accept(TrialsBlocks.W_COPPER_TRAPDOOR.get().asItem());
				tabData.accept(TrialsBlocks.W_COPPER_DOOR.get().asItem());
				tabData.accept(TrialsBlocks.W_COPPER_GRATE.get().asItem());
				tabData.accept(Blocks.OXIDIZED_COPPER.asItem());
				tabData.accept(TrialsBlocks.OXI_CHISELED_COPPER.get().asItem());
				tabData.accept(TrialsBlocks.OXI_COPPER_BULB.get().asItem());
				tabData.accept(Blocks.OXIDIZED_CUT_COPPER.asItem());
				tabData.accept(Blocks.OXIDIZED_CUT_COPPER_STAIRS.asItem());
				tabData.accept(Blocks.OXIDIZED_CUT_COPPER_SLAB.asItem());
				tabData.accept(TrialsBlocks.OXI_COPPER_TRAPDOOR.get().asItem());
				tabData.accept(TrialsBlocks.OXI_COPPER_DOOR.get().asItem());
				tabData.accept(TrialsBlocks.OXI_COPPER_GRATE.get().asItem());
				tabData.accept(Blocks.WAXED_COPPER_BLOCK.asItem());
				tabData.accept(TrialsBlocks.WAXED_CHISELED_COPPER.get().asItem());
				tabData.accept(TrialsBlocks.WAXED_COPPER_BULB.get().asItem());
				tabData.accept(Blocks.WAXED_CUT_COPPER.asItem());
				tabData.accept(Blocks.WAXED_CUT_COPPER_STAIRS.asItem());
				tabData.accept(Blocks.WAXED_CUT_COPPER_SLAB.asItem());
				tabData.accept(TrialsBlocks.WAXED_COPPER_TRAPDOOR.get().asItem());
				tabData.accept(TrialsBlocks.WAXED_COPPER_DOOR.get().asItem());
				tabData.accept(TrialsBlocks.WAXED_COPPER_GRATE.get().asItem());
				tabData.accept(Blocks.WAXED_EXPOSED_COPPER.asItem());
				tabData.accept(TrialsBlocks.WAXED_EX_CHISELED_COPPER.get().asItem());
				tabData.accept(TrialsBlocks.WAXED_EX_COPPER_BULB.get().asItem());
				tabData.accept(Blocks.WAXED_EXPOSED_CUT_COPPER.asItem());
				tabData.accept(Blocks.WAXED_EXPOSED_CUT_COPPER_STAIRS.asItem());
				tabData.accept(Blocks.WAXED_EXPOSED_CUT_COPPER_SLAB.asItem());
				tabData.accept(TrialsBlocks.WAXED_EX_COPPER_TRAPDOOR.get().asItem());
				tabData.accept(TrialsBlocks.WAXED_EX_COPPER_DOOR.get().asItem());
				tabData.accept(TrialsBlocks.WAXED_EX_COPPER_GRATE.get().asItem());
				tabData.accept(Blocks.WAXED_WEATHERED_COPPER.asItem());
				tabData.accept(TrialsBlocks.WAXED_W_CHISELED_COPPER.get().asItem());
				tabData.accept(TrialsBlocks.WAXED_W_COPPER_BULB.get().asItem());
				tabData.accept(Blocks.WAXED_WEATHERED_CUT_COPPER.asItem());
				tabData.accept(Blocks.WAXED_WEATHERED_CUT_COPPER_STAIRS.asItem());
				tabData.accept(Blocks.WAXED_WEATHERED_CUT_COPPER_SLAB.asItem());
				tabData.accept(TrialsBlocks.WAXED_W_COPPER_TRAPDOOR.get().asItem());
				tabData.accept(TrialsBlocks.WAXED_W_COPPER_DOOR.get().asItem());
				tabData.accept(TrialsBlocks.WAXED_W_COPPER_GRATE.get().asItem());
				tabData.accept(Blocks.WAXED_OXIDIZED_COPPER.asItem());
				tabData.accept(TrialsBlocks.WAXED_OXI_CHISELED_COPPER.get().asItem());
				tabData.accept(TrialsBlocks.WAXED_OXI_COPPER_BULB.get().asItem());
				tabData.accept(Blocks.WAXED_OXIDIZED_CUT_COPPER.asItem());
				tabData.accept(Blocks.WAXED_OXIDIZED_CUT_COPPER_STAIRS.asItem());
				tabData.accept(Blocks.WAXED_OXIDIZED_CUT_COPPER_SLAB.asItem());
				tabData.accept(TrialsBlocks.WAXED_OXI_COPPER_TRAPDOOR.get().asItem());
				tabData.accept(TrialsBlocks.WAXED_OXI_COPPER_DOOR.get().asItem());
				tabData.accept(TrialsBlocks.WAXED_OXI_COPPER_GRATE.get().asItem());
			}).build());
}